services:
  - type: worker
    name: elite-scraper
    env: python
    plan: starter
    buildCommand: >
      pip install -r requirements.txt &&
      PLAYWRIGHT_BROWSERS_PATH=/mnt/cache/playwright playwright install chromium
    startCommand: python scrap_players.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /mnt/cache/playwright
