services:
  - type: worker
    name: elite-scraper
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt && playwright install chromium
    startCommand: python scrap_players.py
