services:
  - type: worker
    name: elite-scraper
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt &&
      playwright install chromium
    startCommand: python scrap_players.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: .cache/ms-playwright
