services:
  - type: worker
    name: elite-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      PLAYWRIGHT_BROWSERS_PATH=/mnt/cache/playwright playwright install
    startCommand: python scrap_players.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /mnt/cache/playwright
    disk:
      name: scraper-cache
      mountPath: /mnt/cache
      sizeGB: 1
